# Generated by Django 4.2 on 2023-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_orderdetail_stripe_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="stripe_payment_intent",
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
