# Generated by Django 4.2 on 2023-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_orderdetail_stripe_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
